"""공개할 전략 정의 (큐레이션).

새 전략을 추가하려면 여기에 항목을 추가하고 배치를 다시 돌리면 된다.
형식은 engine.py 상단 주석 참고. 이벤트 목록은 events.py의 build_events 키.
지표 조건(when)에 쓸 수 있는 컬럼: rsi, macd, macd_signal, macd_hist,
pct_b, bb_width, close 등 indicators.core.compute_indicators가 만드는 모든 컬럼.
"""

STRATEGIES: list[dict] = [
    # --- 품질 필터 실험(2026-07-23)에서 유효성이 확인된 조합 ---
    # 발견: 패턴 돌파 + 품질 필터는 '대형주(시총 상위 300)'에서 유효하고,
    # 전 종목(소형주 포함)에서는 무효/역효과. universe: large300 = 대형주 한정.
    {
        "id": "flag-bull-large-q",
        "name": "[대형주] 상승 플래그 + 거래량 1.5배 + 추세 위",
        "trigger": "pat_flag_bull",
        "when": [["vol_ratio20", ">=", 1.5], ["ma120_gap", ">=", 0]],
        "confirm": None,
        "universe": "large300",
        "desc": "시총 상위 300 종목에서 급등 깃대 후 조정 돌파를 거래량·추세로 확인. 실험에서 가장 강한 조합.",
    },
    {
        "id": "cup-handle-large-q",
        "name": "[대형주] 컵앤핸들 + 거래량 1.5배",
        "trigger": "pat_cup_handle",
        "when": [["vol_ratio20", ">=", 1.5]],
        "confirm": None,
        "universe": "large300",
        "desc": "대형주 컵앤핸들 돌파를 거래량으로 확인. 무필터 대비 개선이 뚜렷했던 조합.",
    },
    {
        "id": "hs-inv-large-q",
        "name": "[대형주] 역헤드앤숄더 + 추세 위",
        "trigger": "pat_hs_inv",
        "when": [["ma120_gap", ">=", 0]],
        "confirm": None,
        "universe": "large300",
        "desc": "대형주에서 120일선 위(장기 추세 순방향)일 때의 역H&S 돌파만 선별.",
    },
    {
        "id": "double-bottom-large-q",
        "name": "[대형주] 쌍바닥 + 거래량 1.5배 + 추세 위",
        "trigger": "pat_double_bottom",
        "when": [["vol_ratio20", ">=", 1.5], ["ma120_gap", ">=", 0]],
        "confirm": None,
        "universe": "large300",
        "desc": "대형주 쌍바닥 돌파를 거래량·추세로 확인.",
    },
    {
        "id": "engulf-bull",
        "name": "상승 장악형 (하락 후)",
        "trigger": "cdl_engulf_bull",
        "confirm": None,
        "desc": "하락 흐름에서 양봉 몸통이 전봉 음봉을 완전히 감싼 날 진입. 대표적 단기 반전 캔들.",
    },
    {
        "id": "morning-star",
        "name": "샛별형 (3봉 반전)",
        "trigger": "cdl_morning",
        "confirm": None,
        "desc": "큰 음봉 → 작은 몸통 → 큰 양봉이 첫 봉 중간을 회복한 3봉 반전 완성일 진입.",
    },
    {
        "id": "flag-bull-contrarian",
        "name": "[발견] 상승 플래그 — 하락추세 중 (역발상)",
        "trigger": "pat_flag_bull",
        "when": [["ma120_gap", "<", 0]],
        "confirm": None,
        "desc": "실험 중 발견된 역발상 조합: 장기 추세 아래에서 나온 급등-조정-재돌파. 하락장 반등 국면 특성일 수 있어 해석에 주의.",
    },
    {
        "id": "div-bull",
        "name": "상승 다이버전스 (단독)",
        "trigger": "div_reg_bull",
        "confirm": None,
        "desc": "가격 저점은 낮아지고 RSI 저점은 높아진 반전 신호. 확정일 종가 진입.",
    },
    {
        # 연속 다이버전스의 값어치를 재는 대조군. 위 'div-bull'(2연속 포함 전체)과
        # 나란히 놓고 봐야 "3연속이 실제로 나은가"를 판단할 수 있다.
        "id": "div-bull-x3",
        # 이름에 "3회"를 넣지 않는다 — 기준은 저점 개수이고, 저점 3개는
        # 다이버전스 2쌍이라 횟수로 읽히면 과장된다.
        "name": "상승 다이버전스 연속",
        "trigger": "div_reg_bull_x3",
        "confirm": None,
        "desc": "가격 저점이 계속 낮아지는데 RSI 저점은 계속 높아지는 상태가 세 저점 이상 이어진 뒤 진입. 한 번만 어긋난 경우(div-bull)와 성과를 비교해 보세요.",
    },
    {
        "id": "div-bear-x3",
        "name": "하락 다이버전스 연속",
        "trigger": "div_reg_bear_x3",
        "confirm": None,
        "desc": "가격 고점이 계속 높아지는데 RSI 고점은 계속 낮아지는 상태가 세 고점 이상 이어진 뒤의 성과. 하락 신호이므로 수익률이 낮게 나오는 것이 정상입니다.",
    },
    {
        "id": "div-bull-golden-rsi40",
        "name": "상승 다이버전스 → 10일 내 골든크로스 + RSI≥40",
        "trigger": "div_reg_bull",
        "confirm": {
            "event": "macd_golden",
            "within_days": 10,
            "when": [["rsi", ">=", 40]],
        },
        "desc": "다이버전스 발생 후 MACD 골든크로스로 반전을 확인하고, 확인 시점 RSI가 40 이상(반등 동력)일 때만 진입.",
    },
    {
        "id": "golden",
        "name": "MACD 골든크로스 (단독)",
        "trigger": "macd_golden",
        "confirm": None,
        "desc": "MACD선이 시그널선을 상향 돌파한 날 진입.",
    },
    {
        "id": "golden-below-zero",
        "name": "저점 골든크로스 (MACD<0에서 발생)",
        "trigger": "macd_golden",
        "when": [["macd", "<", 0]],
        "confirm": None,
        "desc": "0선 아래(하락 후 저점권)에서 나온 골든크로스만 선별.",
    },
    {
        "id": "zero-up",
        "name": "MACD 0선 상향 돌파",
        "trigger": "macd_zero_up",
        "confirm": None,
        "desc": "중기 추세가 상승으로 전환되는 구간 진입.",
    },
    {
        "id": "oversold-exit",
        "name": "과매도 탈출 (RSI 30 상향 재돌파)",
        "trigger": "rsi_cross_up_30",
        "confirm": None,
        "desc": "RSI가 30 아래에서 위로 올라온 날 진입 (과매도 반등 초입).",
    },
    {
        "id": "bb-lower-rsi-recover",
        "name": "볼린저 하단 터치 → 5일 내 RSI 30 회복",
        "trigger": "bb_lower_touch",
        "confirm": {
            "event": "rsi_cross_up_30",
            "within_days": 5,
            "when": [],
        },
        "desc": "하단 터치(과매도) 후 며칠 안에 RSI가 회복되는 흐름을 확인하고 진입.",
    },
    {
        "id": "squeeze-golden",
        "name": "볼린저 스퀴즈 상태에서 골든크로스",
        "trigger": "macd_golden",
        "when": [["bb_width", "<", 0.1]],
        "confirm": None,
        "desc": "밴드폭이 좁은(변동성 축소) 상태에서 나온 골든크로스 — 방향 분출 초입 후보.",
    },
    {
        "id": "double-bottom",
        "name": "쌍바닥 돌파 (넥라인 상향 돌파일 진입)",
        "trigger": "pat_double_bottom",
        "confirm": None,
        "desc": "두 바닥이 ±3% 안에서 형성되고 넥라인(사이 반등 고점)을 종가로 돌파한 날 진입.",
    },
    {
        "id": "cup-handle",
        "name": "컵앤핸들 돌파 (우림 상향 돌파일 진입)",
        "trigger": "pat_cup_handle",
        "confirm": None,
        "desc": "U자 컵(깊이 10~50%, 둥근 바닥 검증)과 얕은 핸들 후 우측 림을 종가로 돌파한 날 진입.",
    },
    {
        "id": "hs-inverse",
        "name": "역헤드앤숄더 돌파",
        "trigger": "pat_hs_inv",
        "confirm": None,
        "desc": "어깨-머리-어깨 바닥 구조 후 넥라인을 상향 돌파한 날 진입.",
    },
    {
        "id": "triple-bottom",
        "name": "3중바닥 돌파",
        "trigger": "pat_triple_bottom",
        "confirm": None,
        "desc": "유사한 저점 3개 후 넥라인을 상향 돌파한 날 진입.",
    },
    {
        "id": "round-bottom",
        "name": "라운드 바텀 돌파",
        "trigger": "pat_round_bottom",
        "confirm": None,
        "desc": "완만한 접시형 바닥 후 림 레벨을 돌파한 날 진입.",
    },
    {
        "id": "wedge-fall",
        "name": "하락쐐기 상향 돌파",
        "trigger": "pat_wedge_fall",
        "confirm": None,
        "desc": "하락 수렴 쐐기의 위 추세선을 상향 돌파한 날 진입.",
    },
    {
        "id": "flag-bull",
        "name": "상승 플래그/페넌트 돌파",
        "trigger": "pat_flag_bull",
        "confirm": None,
        "desc": "급등 깃대 후 얕은 조정을 거쳐 깃대 고점을 재돌파한 날 진입.",
    },
    {
        "id": "hs-top",
        "name": "헤드앤숄더 붕괴 — 경고 신호 검증",
        "trigger": "pat_hs_top",
        "confirm": None,
        "desc": "천장 어깨-머리-어깨 후 넥라인 붕괴가 실제 하락으로 이어지는지 확인용.",
    },
    {
        "id": "double-top",
        "name": "더블탑 붕괴 (넥라인 하향 돌파) — 경고 신호 검증",
        "trigger": "pat_double_top",
        "confirm": None,
        "desc": "쌍봉 후 넥라인 붕괴가 실제 하락으로 이어지는지 확인용.",
    },
    {
        "id": "div-bear",
        "name": "하락 다이버전스 (단독) — 경고 신호 검증",
        "trigger": "div_reg_bear",
        "confirm": None,
        "desc": "상승 추세 약화 경고가 실제로 이후 수익률 저하로 이어지는지 확인용.",
    },
    {
        "id": "dead-cross",
        "name": "MACD 데드크로스 (단독) — 대조군",
        "trigger": "macd_dead",
        "confirm": None,
        "desc": "매도 신호 이후의 평균 흐름. 매수 전략들과 비교하는 기준선 역할.",
    },
]
